import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import App from "next/app";
import MobileNavigationBar from "@/app/ui/mobilenavigationbar";
import Image from "next/image";
import { AnimatePresence } from "motion/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    width: 'device-width',
    initialScale: 1,
    viewportFit: 'cover',   // quan trọng!
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative">
        <div className="page-transition-enabled">
            {children}
        </div>
        <div className="absolute bottom-0">
          <MobileNavigationBar />
        </div>
        <div className="fixed inset-0 -z-10 background">  {/* lớp nền toàn màn hình, nằm sau nội dung */}
        </div>
      </body>
    </html>
  );
}
